from graph import Graph

nodos = Graph()

nodos.insert_vertex("Ubuntu",{"tipo":"PC"})
nodos.insert_vertex("Debian",{"tipo":"notebook"})
nodos.insert_vertex("Impresora",{"tipo":"impresora"})
nodos.insert_vertex("Switch1",{"tipo":"switch"})
nodos.insert_vertex("Mint",{"tipo":"PC"})
nodos.insert_vertex("Router1",{"tipo":"router"})
nodos.insert_vertex("Router2",{"tipo":"router"})
nodos.insert_vertex("Router3",{"tipo":"router"})
nodos.insert_vertex("Red hat",{"tipo":"notebook"})
nodos.insert_vertex("Guarani",{"tipo":"servidor"})
nodos.insert_vertex("Switch2",{"tipo":"switch"})
nodos.insert_vertex("Manjaro",{"tipo":"PC"})
nodos.insert_vertex("Fedora",{"tipo":"PC"})
nodos.insert_vertex("Arch",{"tipo":"notebook"})
nodos.insert_vertex("Parrot",{"tipo":"PC"})
nodos.insert_vertex("MongoDB",{"tipo":"servidor"})

nodos.insert_edge("Switch1","Ubuntu",18)    
nodos.insert_edge("Switch1","Debian",17)
nodos.insert_edge("Switch1","Impresora",22)
nodos.insert_edge("Switch1","Mint",80)
nodos.insert_edge("Switch1","Router1",29)
nodos.insert_edge("Router2","Red hat",25)
nodos.insert_edge("Router2","Guarani",9)
nodos.insert_edge("Router2","Router3",50)
nodos.insert_edge("Router2","Router1",37)
nodos.insert_edge("Router3","Router1",43)
nodos.insert_edge("Switch2","Router3",61)
nodos.insert_edge("Switch2","Manjaro",40)
nodos.insert_edge("Switch2","Parrot",12)
nodos.insert_edge("Switch2","MongoDB",5)
nodos.insert_edge("Switch2","Arch",56)
nodos.insert_edge("Switch2","Fedora",3)     
 
print("barrido de profundidad desde Red hat")
nodos.deep_sweep("Red hat")
print()
print("barrido de amplitud desde Red hat")
nodos.amplitude_sweep("Red hat")
print()
print("barrido de profundidad desde Debian")
nodos.deep_sweep("Debian")
print()
print("barrido de amplitud desde Debian")
nodos.amplitude_sweep("Debian")
print()
print("barrido de profundidad desde Arch")
nodos.deep_sweep("Arch")
print()
print("barrido de amplitud desde Arch")
nodos.amplitude_sweep("Arch")
print()

print("mandando a imprimir desde Manjaro")
print(nodos.dijkstra("Manjaro","Impresora"))
print()
print("mandando a imprimir desde Red hat")
print(nodos.dijkstra("Red hat","Impresora"))
print()
print("mandando a imprimir desde Fedora")
print(nodos.dijkstra("Fedora","Impresora"))
print()

print("arbol de expansion minima")
print(nodos.kruskal("Router1"))
print()

PCs=[]
for vertex in nodos:
    if vertex.other_values["tipo"]=="PC":
        PCs.append([vertex.value,nodos.dijkstra(vertex.value,"Guarani")[1]])
print("PC mas cercana al servidor Guarani:")
print(min(PCs, key=lambda x: x[1]))
print()

switch01=[]
for vertex in nodos:
    if (vertex.other_values["tipo"]=="PC" or vertex.other_values["tipo"]=="notebook") and any("Switch1"== edge.value for edge in vertex.edges):
        switch01.append([vertex.value,nodos.dijkstra(vertex.value,"MongoDB")[1]])
print("computadora conectada al Switch1 mas cercana al servidor MongoDB:")
print(min(switch01, key=lambda x: x[1]))
print()

nodos.delete_edge("Switch1","Impresora","value")
nodos.insert_edge("Router2","Impresora",22)
print("barrido de profundidad desde Red hat")
nodos.deep_sweep("Red hat")
print()
print("barrido de amplitud desde Red hat")
nodos.amplitude_sweep("Red hat")
print()
print("barrido de profundidad desde Debian")
nodos.deep_sweep("Debian")
print()
print("barrido de amplitud desde Debian")
nodos.amplitude_sweep("Debian")
print()
print("barrido de profundidad desde Arch")
nodos.deep_sweep("Arch")
print()
print("barrido de amplitud desde Arch")
nodos.amplitude_sweep("Arch")
print()